version: 2.1

<<<<<<< Updated upstream
=======
commands:
  install_python_package:
    steps:
      - run:
          name: Cài đặt python package
          command: |
            pip install pytest requests opencv-python pytest-html

>>>>>>> Stashed changes
jobs:
  build:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "!!!"
  test-video-server-app:
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Cài đặt pytest
          command: |
            pip install pytest requests
      - run:
          name: Test tạo project
          command: |
<<<<<<< Updated upstream
            python -m pytest test_create_project.py
=======
            python -m pytest test_create_project.py --html=test-results/create-project/report.html
      - store_test_results:
          path: test-results/create-project
  
  test-list-projects:
    docker: 
      - image: cimg/python:3.7
    steps:
      - checkout
      - install_python_package
>>>>>>> Stashed changes
      - run:
          name: Test danh sách project
          command: |
            python -m pytest test_list_projects.py
<<<<<<< Updated upstream
=======
      - store_test_results:
          path: test-results/thumbnail-timeline/report.html

  test-delete-project:
    docker: 
      - image: cimg/python:3.7
    steps:
      - checkout
      - install_python_package
>>>>>>> Stashed changes
      - run:
          name: Test xóa project
          command: |
            python -m pytest test_delete_project.py
<<<<<<< Updated upstream
=======
      - store_test_results:
          path: test-results/thumbnail-timeline/report.html

  test-retrieve-project:
    docker: 
      - image: cimg/python:3.7
    steps:
      - checkout
      - install_python_package
>>>>>>> Stashed changes
      - run:
          name: Test truy xuất chi tiết project
          command: |
            python -m pytest test_retrieve_project_details.py
<<<<<<< Updated upstream
=======
      - store_test_results:
          path: test-results/thumbnail-timeline/report.html

  test-duplicate-projects:
    docker: 
      - image: cimg/python:3.7
    steps:
      - checkout
      - install_python_package
>>>>>>> Stashed changes
      - run:
          name: Test nhân bản project
          command: |
            python -m pytest test_duplicate.py
<<<<<<< Updated upstream
=======
      - store_test_results:
          path: test-results/thumbnail-timeline/report.html

  test-preview-thumbnail:
    docker: 
      - image: cimg/python:3.7
    steps:
      - checkout
      - install_python_package
>>>>>>> Stashed changes
      - run:
          name: Test tạo preview thumbnail
          command: |
            python -m pytest test_capture_a_thumbnail_for_preview.py
<<<<<<< Updated upstream
=======
      - store_test_results:
          path: test-results/thumbnail-timeline/report.html

  test-timeline-thumbnail:
    docker: 
      - image: cimg/python:3.7
    steps:
      - checkout
      - install_python_package
      - run:
          name: Test tạo timeline thumbnail
          command: |
            python -m pytest test_capture_a_thumbnail_for_timeline.py
      - store_test_results:
          path: test-results/thumbnail-timeline/report.html

  test-edit-video:
    docker: 
      - image: cimg/python:3.7
    steps:
      - checkout
      - install_python_package
>>>>>>> Stashed changes
      - run:
          name: Test chỉnh sửa video
          command: |
            python -m pytest test_edit_video.py
<<<<<<< Updated upstream
=======
      - store_test_results:
          path: test-results/thumbnail-timeline/report.html
>>>>>>> Stashed changes

workflows:
  build_and_test:
    jobs:
      - test-video-server-app
