version: 2.1

commands:
  install_python_package:
    steps:
      - run:
          name: Cài đặt python package
          command: |
            pip install pytest requests opencv-python pytest-html 

jobs:
  build:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "!!!"

  prepare-report-directory:
    docker:
      - image: cimg/python:3.7
    steps:
      - run:
          name: Chuẩn bị cho báo cáo test
          command: |
            mkdir -p test-results

  test-create-project:
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      - install_python_package
      - run:
          name: Test tạo project
          command: |
            python -m pytest test_create_project.py  -v -s --html=test-results/report.html
      - store_artifacts:
          path: test-results
  
  test-list-projects:
    docker: 
      - image: cimg/python:3.7
    steps:
      - checkout
      - install_python_package
      - run:
          name: Test danh sách project
          command: |
            python -m pytest test_list_projects.py  -v -s --html=test-results/report.html
      - store_artifacts:
          path: test-results

  test-delete-project:
    docker: 
      - image: cimg/python:3.7
    steps:
      - checkout
      - install_python_package
      - run:
          name: Test xóa project
          command: |
            python -m pytest test_delete_project.py  -v -s --html=test-results/report.html
      - store_artifacts:
          path: test-results

  test-retrieve-project:
    docker: 
      - image: cimg/python:3.7
    steps:
      - checkout
      - install_python_package
      - run:
          name: Test truy xuất chi tiết project
          command: |
            python -m pytest test_retrieve_project_details.py  -v -s --html=test-results/report.html
      - store_artifacts:
          path: test-results

  test-duplicate-projects:
    docker: 
      - image: cimg/python:3.7
    steps:
      - checkout
      - install_python_package
      - run:
          name: Test nhân bản project
          command: |
            python -m pytest test_duplicate.py  -v -s --html=test-results/report.html
      - store_artifacts:
          path: test-results

  test-preview-thumbnail:
    docker: 
      - image: cimg/python:3.7
    steps:
      - checkout
      - install_python_package
      - run:
          name: Test tạo preview thumbnail
          command: |
            python -m pytest test_capture_a_thumbnail_for_preview.py  -v -s --html=test-results/report.html
      - store_artifacts:
          path: test-results

  test-timeline-thumbnail:
    docker: 
      - image: cimg/python:3.7
    steps:
      - checkout
      - install_python_package
      - run:
          name: Test tạo timeline thumbnail
          command: |
            python -m pytest test_capture_a_thumbnail_for_timeline.py  -v -s --html=test-results/report.html
      - store_artifacts:
          path: test-results

  test-edit-video:
    docker: 
      - image: cimg/python:3.7
    steps:
      - checkout
      - install_python_package
      - run:
          name: Test chỉnh sửa video
          command: |
            python -m pytest test_edit_video.py  -v -s --html=test-results/report.html
      - store_artifacts:
          path: test-results

workflows:
  video_server_test_pipeline:
    jobs:
      - build:
          filters:
            branches:
              only:
                - testing
      - prepare-report-directory:
          requires:
            - build
      - test-create-project:
          requires:
            - prepare-report-directory
      - test-delete-project:
          requires:
            - prepare-report-directory
      - test-retrieve-project:
          requires:
            - prepare-report-directory
      - test-duplicate-projects:
          requires:
            - prepare-report-directory
      - test-preview-thumbnail:
          requires:
            - prepare-report-directory
      - test-timeline-thumbnail:
          requires:
            - prepare-report-directory
      - test-list-projects:
          requires:
            - test-create-project
            - test-delete-project
            - test-duplicate-projects
            - test-preview-thumbnail
            - test-timeline-thumbnail
      - test-edit-video:
          requires:
            - test-list-projects