version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "!!!"
  prepare-report-directory:
    docker:
      - image: cimg/python:3.7
    steps:
      - run:
          name: Chuẩn bị cho báo cáo test
          command: |
            mkdir -p test-results/thumbnail-timeline
  test-thumbnail-timeline:
    docker: 
      - image: cimg/python:3.7
    steps:
      - run:
          name: Test tạo timeline thumbnail
          command: |
            python -m pytest test_capture_a_thumbnail_for_timeline.py
      - store_test_results:
          path: test-results/thumbnail-timeline
  test-video-server-app:
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Cài đặt pytest
          command: |
            pip install pytest requests opencv-python
      - run:
          name: Test tạo project
          command: |
            python -m pytest test_create_project.py
      - run:
          name: Test danh sách project
          command: |
            python -m pytest test_list_projects.py
      - run:
          name: Test xóa project
          command: |
            python -m pytest test_delete_project.py
      - run:
          name: Test truy xuất chi tiết project
          command: |
            python -m pytest test_retrieve_project_details.py
      - run:
          name: Test nhân bản project
          command: |
            python -m pytest test_duplicate.py
      - run:
          name: Test tạo preview thumbnail
          command: |
            python -m pytest test_capture_a_thumbnail_for_preview.py
      - run:
          name: Test tạo timeline thumbnail
          command: |
            python -m pytest test_capture_a_thumbnail_for_timeline.py
      - run:
          name: Test chỉnh sửa video
          command: |
            python -m pytest test_edit_video.py

workflows:
  video_server_test_pipeline:
    jobs:
      - build
      - prepare-report-directory:
          requires:
            - build
      - test-thumbnail-timeline:
          requires:
            - prepare-report-directory
      - test-video-server-app
